# Managed Flatpak applications
# One application ID per line.
# Existing apps can be added with: wsflatpak manage APP

com.github.tchx84.Flatseal

org.gimp.GIMP

com.mikrotik.WinBox

com.anydesk.Anydesk

us.zoom.Zoom
