# Managed Flatpak applications
# One application ID per line.
# Existing apps can be added with: wsflatpak manage APP

flathub com.github.tchx84.Flatseal

flathub org.gimp.GIMP

flathub com.mikrotik.WinBox

flathub com.anydesk.Anydesk

flathub us.zoom.Zoom


flathub com.obsproject.Studio

flathub org.videolan.VLC

flatpark com.anthropic.ClaudeDesktop

flathub com.mattjakeman.ExtensionManager
