#!/bin/sh
# ws-t2-detach for scripts/local-top/ws-t2-resume (helpws suspend, Hibernate).
PREREQ=""
prereqs() { echo "$PREREQ"; }
case "$1" in
    prereqs) prereqs; exit 0 ;;
esac

. /usr/share/initramfs-tools/hook-functions
copy_file script /usr/local/sbin/ws-t2-detach /usr/sbin/ws-t2-detach
