#
# rEFInd - MacBook Pro 16" 2019
#

#
# THEME
#

include themes/rEFInd-minimal-dark/theme.conf


#
# BEHAVIOUR
#

timeout 2

# Last booted rEFInd entry
default_selection +

# Keep rEFInd variables on the REFIND FAT partition,
# not in T2/Apple NVRAM
use_nvram false


#
# SCANNING
#

scanfor internal,manual

scan_all_linux_kernels true
fold_linux_kernels true

# Ubuntu root is Btrfs subvolume @
also_scan_dirs +,@/boot


#
# REMOVE AUTO-DETECTED DUPLICATES
#

# GRUB will appear only as our manual Recovery entry
dont_scan_dirs +,EFI/ubuntu,EFI/BOOT

# macOS will appear only as our manual macOS entry
dont_scan_volumes "Macintosh HD,Macintosh HD — дані,Preboot,Recovery,VM"


#
# GRAPHICS
#

use_graphics_for osx,linux,grub


#
# NO SECOND ROW
#

showtools


#
# NO TEXT / HINTS / BADGES
#

hideui singleuser,safemode,hwtest,arrows,hints,editor,badges,label


#
# macOS
#
# Confirmed APFS Volume Group:
# BDC97FD7-F737-4A5C-9260-6B5C03DFAA8A
#

menuentry "macOS" {
    icon /EFI/BOOT/themes/rEFInd-minimal-dark/icons/os_mac.png
    volume "Preboot"
    loader \BDC97FD7-F737-4A5C-9260-6B5C03DFAA8A\System\Library\CoreServices\boot.efi
    ostype MacOS
    graphics off
}


#
# GRUB / Btrfs snapshot recovery
#

menuentry "Recovery / Snapshots" {
    icon /EFI/BOOT/themes/rEFInd-minimal-dark/icons/os_linux.png
    volume B17602DD-E010-4C10-A4C0-59019D17E288
    loader /EFI/ubuntu/grubx64.efi
}

